//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace NoiseGeneration
{
	public class BlueScatterNoiseMaker : INoiseMaker
	{
		public BlueScatterNoiseMaker (IFader fader, ILerper lerper, IProximity prox,
		                              Dictionary<int[], ScatterTile> tiles, int dim, int resolution, int hash_size,
		                              int oct_min, int oct_num, float persistence)
		{
		}

		public void GenerateNoise(params int[] coordinates){
		}
	}
}

