//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace NoiseGeneration
{
	public class PerlinQuinticFader : IFader
	{
		public float Fade (float t)
		{
			if (t < 0f || t > 1f)
				throw new ArgumentException ("The argument 't' should be in the interval [0, 1]");
			return (t * t * t * (t * (t * 6f - 15f) + 10f));
		}
	}
}

