//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace NoiseGeneration
{
	public class ValueProximity : IProximity
	{
		//Simple value noise. The hash vaule is just normalised to [0,1).
		public float Proximity (int hash, params float[] coordinates)
		{
			return ((float)hash)/256f;
		}
	}
}

